# Generated by Django 2.1.5 on 2019-04-29 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_auto_20190427_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 14, 44, 10, 316860, tzinfo=utc)),
        ),
    ]
