# Generated by Django 2.1.5 on 2019-04-30 04:59

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0004_auto_20190430_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_details',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 30, 4, 59, 3, 172708, tzinfo=utc)),
        ),
    ]
