# Generated by Django 2.1.7 on 2019-05-13 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0009_auto_20190501_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 18, 19, 30, 537463, tzinfo=utc)),
        ),
    ]
